import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
/* downloads the Geist and Geist Mono fonts from Google Fonts and sets them up for use in the application */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/* defines metadata for the application, including the title and description */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
/* defines the root layout component for the application to then be overlaid with global styles */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
